name: Upload Charm Docs
description: Upload charm documentation to charmhub
author: David Andersson
inputs:
  dry_run:
    description: |
      If enabled, only log the changes that would be made.
    default: false
    required: false
    type: boolean
  delete_topics:
    description: |
      Whether to delete topics from the documentation server if they are no
      longer needed.
    default: true
    required: false
    type: boolean
  discourse_host:
    description: The base path(hostname) to the discourse server.
    required: true
    type: string
  discourse_api_username:
    description: |
      The discourse API username to use for interactions with the server.
    required: true
    type: string
  discourse_api_key:
    description: |
      The discourse API key to use for interactions with the server.
    required: true
    type: string
  discourse_category_id:
    description: The category identifier to use on discourse for all topics.
    default: 41
    required: false
    type: integer
  github_token:
    description: |
      The github access token (secrets.GITHUB_TOKEN) to create pull request on Github and retrieve
      the current documentation
    required: true
    type: string
  base_tag_name:
    description: |
      The name of the tag that contains the documentation after it has been uploaded to
      discourse.
    required: false
    type: string
    default: "upload-charm-docs/base-content"
outputs:
  urls_with_actions:
    description: |
      A JSON map with the urls and the actions that have been taken against
      them.
  index_url:
    description: The URL to the documentation index page.
runs:
  using: docker
  image: Dockerfile
