# Copyright 2023 Canonical Ltd.
# See LICENSE file for licensing details.
name: Upload Charm Docs
description: Upload charm documentation to charmhub
author: David Andersson
inputs:
  dry_run:
    description: |
      If enabled, only log the changes that would be made.
    default: false
    required: false
    type: boolean
  delete_topics:
    description: |
      Whether to delete topics from the documentation server if they are no
      longer needed.
    default: true
    required: false
    type: boolean
  discourse_host:
    description: The base path(hostname) to the discourse server.
    required: true
    type: string
  discourse_api_username:
    description: |
      The discourse API username to use for interactions with the server.
    required: true
    type: string
  discourse_api_key:
    description: |
      The discourse API key to use for interactions with the server.
    required: true
    type: string
  discourse_category_id:
    description: The category identifier to use on discourse for all topics.
    default: 41
    required: false
    type: integer
  github_token:
    description: |
      The github access token (secrets.GITHUB_TOKEN) to create pull request on Github and retrieve
      the current documentation.
    required: true
    type: string
  base_branch:
    description: |
      The name of the base branch for the repository.
    default: main
    required: false
    type: string
  commit_sha:
    description: |
      The SHA of the commit to be used when running the action. If not provided, it falls back to 
      the pull request head SHA or (if outside of a PR) to the value of the environment 
      variable GITHUB_SHA.
    required: false
    type: string
outputs:
  index_url:
    description: |
      A JSON map with the urls and the actions that have been taken against
      them.
  topics:
    description: |
      A JSON map with the urls and the actions that have been taken against
      them.
  pr_link:
    description: |
      A link of the community contribution PR.
  pr_action:
    description: |
      A description of which actions for the PR has been taken among created, closed and updated.
runs:
  using: docker
  image: Dockerfile
