name: Upload Charm Docs
description: Upload charm documentation to charmhub
author: David Andersson
inputs:
  create_new_topic:
    description: |
      Whether to create a new topic and commit it back to the repository if the
      docs key in metadata.yaml either does not exist or is empty. Defaults to
      not creating a new topic in which case an error is returned.
    default: false
    required: false
    type: boolean
  discourse_host:
    description: The discourse host name.
    required: true
    type: string
  discourse_category_id:
    description: The category identifier to use on discourse for all topics.
    default: 41
    required: false
    type: integer
runs:
  using: docker
  image: Dockerfile
