name: Upload Charm Docs
description: Upload charm documentation to charmhub
author: David Andersson
inputs:
  dry_run:
    description: |
      If enabled, only log the changes that would be made.
    default: false
    required: false
    type: boolean
  delete_topics:
    description: |
      Whether to delete topics from the documentation server if they are no
      longer needed.
    default: true
    required: false
    type: boolean
  discourse_host:
    description: The discourse host name.
    required: true
    type: string
  discourse_api_username:
    description: |
      The discourse API username to use for interactions with the server.
    required: true
    type: string
  discourse_api_key:
    description: |
      The discourse API key to use for interactions with the server.
    required: true
    type: string
  discourse_category_id:
    description: The category identifier to use on discourse for all topics.
    default: 41
    required: false
    type: integer
  github_token:
    description: |
      The github access token (${{ secrets.GITHUB_TOKEN }}) to create pull request on Github.
      Required if running in migration mode.
    default: ${{ github.token }}
    required: false
    type: string
  branch_name:
    description: Branch name to create pull request branch.
    default: upload-charm-docs
    required: false
    type: string
outputs:
  urls_with_actions:
    description: |
      A JSON map with the urls and the actions that have been taken against
      them.
  index_url:
    description: The URL to the documentation index page.
  discourse_config:
    description: |
      The configuration used by the action to interact with the discourse
      server.
runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - run: |
        python -m pip install -r ${{ github.action_path }}/requirements.txt && \
        INPUT_DRY_RUN=${{ inputs.dry_run }} \
        INPUT_DELETE_TOPICS=${{ inputs.delete_topics }} \
        INPUT_DISCOURSE_HOST=${{ inputs.discourse_host }} \
        INPUT_DISCOURSE_CATEGORY_ID=${{ inputs.discourse_category_id }} \
        INPUT_DISCOURSE_API_USERNAME=${{ inputs.discourse_api_username }} \
        INPUT_DISCOURSE_API_KEY=${{ inputs.discourse_api_key }} \
        ${{ github.action_path }}/main.py
      shell: bash
    - uses: peter-evans/create-pull-request@v4
      with:
        branch: "docs/migration-demo"
        title: "[docs] Documentation migration demo"
        body: "This is a test for demo purpose, do not merge."
