name: Upload Charm Docs
description: Upload charm documentation to charmhub
author: David Andersson
inputs:
  delete_topics:
    description: |
      Whether to delete topics from the documentation server if they are no
      longer needed.
    default: true
    required: false
    type: boolean
  draft_mode:
    description: |
      If enabled, only log the changes that would be made.
    default: false
    required: false
    type: boolean
  discourse_host:
    description: The discourse host name.
    required: true
    type: string
  discourse_api_username:
    description: |
      The discourse API username to use for interactions with the server.
    required: true
    type: string
  discourse_api_key:
    description: |
      The discourse API key to use for interactions with the server.
    required: true
    type: string
  discourse_category_id:
    description: The category identifier to use on discourse for all topics.
    default: 41
    required: false
    type: integer
outputs:
  urls_with_actions:
    description: |
      A JSON map with the urls and the actions that have been taken against
      them.
  index_url:
    description: The URL to the documentation index page.
  discourse_config:
    description: |
      The configuration used by the action to interact with the discourse
      server.
runs:
  using: docker
  image: Dockerfile
